(ns views.create-order
  "Create order view - manual order creation for testing."
  (:require [re-frame.core :as rf]
            [reagent.core :as r]
            [monitor.components.forms :as forms]))

(defn create-order-form []
  (let [customer-id (r/atom "")
        product-id (r/atom "PROD-001")
        quantity (r/atom "1")
        unit-price (r/atom "100.00")
        submitting? (r/atom false)]
    (fn []
      [:div.create-order-form
       [:h3 "Create Test Order"]
       [:p.description "Create a test order to simulate the order processor. This will publish directly to the Kafka 'orders' topic."]

       [:div.form-grid
        [forms/number-input
         {:id "customer-id"
          :label "Customer ID"
          :value @customer-id
          :placeholder "1-100"
          :min 1
          :max 100
          :on-change #(reset! customer-id (-> % .-target .-value))
          :required? true}]

        [forms/select-input
         {:id "product-id"
          :label "Product"
          :value @product-id
          :options [{:value "PROD-001" :label "PROD-001"}
                    {:value "PROD-002" :label "PROD-002"}
                    {:value "PROD-003" :label "PROD-003"}
                    {:value "PROD-004" :label "PROD-004"}
                    {:value "PROD-005" :label "PROD-005"}]
          :on-change #(reset! product-id (-> % .-target .-value))
          :required? true}]

        [forms/number-input
         {:id "quantity"
          :label "Quantity"
          :value @quantity
          :placeholder "1-20"
          :min 1
          :max 20
          :on-change #(reset! quantity (-> % .-target .-value))
          :required? true}]

        [forms/number-input
         {:id "unit-price"
          :label "Unit Price ($)"
          :value @unit-price
          :placeholder "10.00-1000.00"
          :min 10
          :max 1000
          :step 0.01
          :on-change #(reset! unit-price (-> % .-target .-value))
          :required? true}]]

       [:div.form-actions
        [forms/button
         {:label (if @submitting? "Creating..." "Create Order")
          :variant :primary
          :loading? @submitting?
          :on-click #(do
                       (reset! submitting? true)
                       ;; TODO: Implementar endpoint POST /api/orders
                       (js/setTimeout
                        (fn []
                          (reset! submitting? false)
                          (js/alert (str "Order created!\nCustomer: " @customer-id
                                         "\nProduct: " @product-id
                                         "\nQuantity: " @quantity
                                         "\nPrice: $" @unit-price
                                         "\n\nNote: This is a mock - API endpoint not implemented yet.")))
                        1000))}]]

       [:div.help-section
        [:h4 "ℹ️ About Order Creation"]
        [:p "In the current architecture, orders are automatically generated by the order-processor at a rate of 10/second."]
        [:p "This manual creation feature would require:"]
        [:ul
         [:li "Backend endpoint: POST /api/orders"]
         [:li "Kafka producer in the monitor service"]
         [:li "Validation and error handling"]
         [:li "Real-time feedback via WebSocket"]]
        [:p [:strong "Current status:"] " Mock implementation - shows how the UI would work."]]])))

(defn create-order-view []
  [:div.create-order-view
   [:div.view-header
    [:h1 "Create Order"]
    [:p.subtitle "Manually create test orders"]]
   [:div.create-order-content
    [create-order-form]]])