(ns shared.specs
  "Shared specifications and data validation rules across all microservices.
     
     Used by:
     - order-processor: Order creation and processing;
     - query-processor: Analytics and statistics;
     - registry-processor: Order validation and registration;
     - monitor: Web dashboard and monitoring."
  #?(:clj (:require [clojure.spec.alpha :as s])
     :cljs (:require [cljs.spec.alpha :as s])))

;; =============================================================================
;; Common Order Specs
;; =============================================================================

(s/def ::order-id
  #(and (string? %) (not (boolean (empty? %))))) ;; "Unique order identifier as non-empty string"
(s/def ::customer-id
  pos-int?) ;; "Customer identifier as positive integer"
(s/def ::product-id
  #(and (string? %) (not (boolean (empty? %))))) ;; "Product identifier as non-empty string"
(s/def ::quantity
  pos-int?) ;; "Order quantity as positive integer"
(s/def ::unit-price
  (s/and number? pos?)) ;; "Product unit price as positive number"
(s/def ::total
  (s/and number? pos?))  ;; "Order total amount as positive number"
(s/def ::timestamp
  pos-int?) ;; "Timestamp in milliseconds as positive integer"
(s/def ::status
  #{"pending" "accepted" "denied"}) ;; "Order status from predefined set of values" 

(s/def ::order
  ;; "Complete order specification with all required attributes.
  ;;  Represents the base order structure used across all services."
  (s/keys :req-un [::order-id
                   ::customer-id
                   ::product-id
                   ::quantity
                   ::unit-price
                   ::total
                   ::timestamp
                   ::status]))

;; =============================================================================
;; Customer Stats Specs - Analytics
;; =============================================================================

(s/def ::total-orders
  nat-int?) ;; "Total number of orders placed by customer (non-negative integer)"

(s/def ::total-spent
  (s/and number? (complement neg?))) ;; "Total amount spent by customer (non-negative number)"

(s/def ::last-order-id
  (s/nilable string?)) ;; "ID of the most recent order, nullable for new customers"

(s/def ::last-order-timestamp
  (s/nilable pos-int?)) ;; "Timestamp of most recent order, nullable for new customers"

(s/def ::first-order-timestamp
  pos-int?) ;; "Timestamp of first order placed by customer"

(s/def ::customer-stats
  ;; "Customer statistics and analytics data.
  ;;  Generated by query-processor for customer insights."
  (s/keys :req-un [::customer-id
                   ::total-orders
                   ::total-spent
                   ::last-order-id
                   ::last-order-timestamp
                   ::first-order-timestamp]))

;; =============================================================================
;; Product Stats Specs -  Analytics
;; =============================================================================

(s/def ::total-quantity
  nat-int?) ;; "Total quantity sold across all orders (non-negative integer)"
(s/def ::total-revenue
  (s/and number? (complement neg?))) ;; "Total revenue generated from product sales (non-negative number)"
(s/def ::order-count
  nat-int?) ;; "Number of distinct orders containing this product (non-negative integer)"
(s/def ::avg-quantity
  (s/and number? (complement neg?))) ;; "Average quantity per order (non-negative number)"
(s/def ::product-stats
  ;; "Product statistics and sales analytics.
  ;;  Generated by query-processor for product performance analysis."
  (s/keys :req-un [::product-id
                   ::total-quantity
                   ::total-revenue
                   ::order-count
                   ::avg-quantity
                   ::last-order-timestamp]))

;; =============================================================================
;; Registered (Orders) Specs - Analytics
;; =============================================================================

(s/def ::registered-at
  pos-int?) ;; "Timestamp when order was registered in the system"

(s/def ::updated-at
  (s/nilable pos-int?)) ;; "Timestamp when order was last updated"

(s/def ::version
  pos-int?) ;; "Version number for optimistic concurrency control"

(s/def ::validation-passed
  boolean?) ;; "Flag indicating whether business validation passed"

(s/def ::registered-order
  ;; "Enhanced order record as stored in the registry.
  ;;  Includes system-generated metadata and validation results."
  (s/keys :req-un [::order-id
                   ::customer-id
                   ::product-id
                   ::quantity
                   ::total
                   ::status
                   ::registered-at
                   ::version
                   ::validation-passed]
          :opt-un [::updated-at]))

;; =============================================================================
;; Validation Functions
;; =============================================================================

(defn valid-order?
  "Validate if data conforms to base order specification.
   Returns true if valid, false otherwise."
  [order]
  (s/valid? ::order order))

(defn valid-customer-stats?
  "Validate if data conforms to customer statistics specification.
   Returns true if valid, false otherwise."
  [stats]
  (s/valid? ::customer-stats stats))

(defn valid-product-stats?
  "Validate if data conforms to product statistics specification.
   Returns true if valid, false otherwise."
  [stats]
  (s/valid? ::product-stats stats))

(defn valid-registered-order?
  "Validate if data conforms to registered order specification.
   Returns true if valid, false otherwise."
  [order]
  (s/valid? ::registered-order order))

(defn explain-error
  "Generate explanation to user of validation errors.
   Returns string describing why data failed validation."
  [spec data]
  (s/explain-str spec data))

;; =============================================================================
;; Business Rules (shared constants)
;; =============================================================================

(def business-rules
  ;; "Business validation rules and constraints used by registry-processor.
  ;;  These constants define the operational boundaries for order processing."
  {:min-quantity 1
   :max-quantity 1000
   :min-total 1.0
   :max-total 100000.0
   :price-tolerance 0.01    ; Allowable difference between calculated and provided total
   :valid-statuses #{"pending" "accepted" "denied"}})